# Generated by Django 3.1.4 on 2020-12-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='utube_link',
            field=models.CharField(default='youtubrlink', max_length=255),
        ),
    ]
